/*
AVNU API

REST API documentation for accessing liquidity on Layer 2.  AVNU is a decentralized exchange protocol enabling the fastest and the most efficient operations in DeFi for Layer 2 with better pricing, zero slippage, MEV-protection and gasless trading.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the Call type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Call{}

// Call The list of calls that will be executed
type Call struct {
	// Contract's address
	ContractAddress string `json:"contractAddress"`
	// Entrypoint (string format)
	Entrypoint string `json:"entrypoint"`
	// calldata (list of felt)
	Calldata []string `json:"calldata"`
}

type _Call Call

// NewCall instantiates a new Call object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCall(contractAddress string, entrypoint string, calldata []string) *Call {
	this := Call{}
	this.ContractAddress = contractAddress
	this.Entrypoint = entrypoint
	this.Calldata = calldata
	return &this
}

// NewCallWithDefaults instantiates a new Call object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCallWithDefaults() *Call {
	this := Call{}
	return &this
}

// GetContractAddress returns the ContractAddress field value
func (o *Call) GetContractAddress() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ContractAddress
}

// GetContractAddressOk returns a tuple with the ContractAddress field value
// and a boolean to check if the value has been set.
func (o *Call) GetContractAddressOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ContractAddress, true
}

// SetContractAddress sets field value
func (o *Call) SetContractAddress(v string) {
	o.ContractAddress = v
}

// GetEntrypoint returns the Entrypoint field value
func (o *Call) GetEntrypoint() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Entrypoint
}

// GetEntrypointOk returns a tuple with the Entrypoint field value
// and a boolean to check if the value has been set.
func (o *Call) GetEntrypointOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Entrypoint, true
}

// SetEntrypoint sets field value
func (o *Call) SetEntrypoint(v string) {
	o.Entrypoint = v
}

// GetCalldata returns the Calldata field value
func (o *Call) GetCalldata() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.Calldata
}

// GetCalldataOk returns a tuple with the Calldata field value
// and a boolean to check if the value has been set.
func (o *Call) GetCalldataOk() ([]string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Calldata, true
}

// SetCalldata sets field value
func (o *Call) SetCalldata(v []string) {
	o.Calldata = v
}

func (o Call) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Call) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["contractAddress"] = o.ContractAddress
	toSerialize["entrypoint"] = o.Entrypoint
	toSerialize["calldata"] = o.Calldata
	return toSerialize, nil
}

func (o *Call) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"contractAddress",
		"entrypoint",
		"calldata",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCall := _Call{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCall)

	if err != nil {
		return err
	}

	*o = Call(varCall)

	return err
}

type NullableCall struct {
	value *Call
	isSet bool
}

func (v NullableCall) Get() *Call {
	return v.value
}

func (v *NullableCall) Set(val *Call) {
	v.value = val
	v.isSet = true
}

func (v NullableCall) IsSet() bool {
	return v.isSet
}

func (v *NullableCall) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCall(val *Call) *NullableCall {
	return &NullableCall{value: val, isSet: true}
}

func (v NullableCall) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCall) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


