/*
AVNU API

REST API documentation for accessing liquidity on Layer 2.  AVNU is a decentralized exchange protocol enabling the fastest and the most efficient operations in DeFi for Layer 2 with better pricing, zero slippage, MEV-protection and gasless trading.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the TypedDataMessageEntriesInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &TypedDataMessageEntriesInner{}

// TypedDataMessageEntriesInner struct for TypedDataMessageEntriesInner
type TypedDataMessageEntriesInner struct {
	Value map[string]interface{} `json:"value,omitempty"`
	Key *string `json:"key,omitempty"`
}

// NewTypedDataMessageEntriesInner instantiates a new TypedDataMessageEntriesInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTypedDataMessageEntriesInner() *TypedDataMessageEntriesInner {
	this := TypedDataMessageEntriesInner{}
	return &this
}

// NewTypedDataMessageEntriesInnerWithDefaults instantiates a new TypedDataMessageEntriesInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTypedDataMessageEntriesInnerWithDefaults() *TypedDataMessageEntriesInner {
	this := TypedDataMessageEntriesInner{}
	return &this
}

// GetValue returns the Value field value if set, zero value otherwise.
func (o *TypedDataMessageEntriesInner) GetValue() map[string]interface{} {
	if o == nil || IsNil(o.Value) {
		var ret map[string]interface{}
		return ret
	}
	return o.Value
}

// GetValueOk returns a tuple with the Value field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TypedDataMessageEntriesInner) GetValueOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.Value) {
		return map[string]interface{}{}, false
	}
	return o.Value, true
}

// HasValue returns a boolean if a field has been set.
func (o *TypedDataMessageEntriesInner) HasValue() bool {
	if o != nil && !IsNil(o.Value) {
		return true
	}

	return false
}

// SetValue gets a reference to the given map[string]interface{} and assigns it to the Value field.
func (o *TypedDataMessageEntriesInner) SetValue(v map[string]interface{}) {
	o.Value = v
}

// GetKey returns the Key field value if set, zero value otherwise.
func (o *TypedDataMessageEntriesInner) GetKey() string {
	if o == nil || IsNil(o.Key) {
		var ret string
		return ret
	}
	return *o.Key
}

// GetKeyOk returns a tuple with the Key field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TypedDataMessageEntriesInner) GetKeyOk() (*string, bool) {
	if o == nil || IsNil(o.Key) {
		return nil, false
	}
	return o.Key, true
}

// HasKey returns a boolean if a field has been set.
func (o *TypedDataMessageEntriesInner) HasKey() bool {
	if o != nil && !IsNil(o.Key) {
		return true
	}

	return false
}

// SetKey gets a reference to the given string and assigns it to the Key field.
func (o *TypedDataMessageEntriesInner) SetKey(v string) {
	o.Key = &v
}

func (o TypedDataMessageEntriesInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o TypedDataMessageEntriesInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Value) {
		toSerialize["value"] = o.Value
	}
	if !IsNil(o.Key) {
		toSerialize["key"] = o.Key
	}
	return toSerialize, nil
}

type NullableTypedDataMessageEntriesInner struct {
	value *TypedDataMessageEntriesInner
	isSet bool
}

func (v NullableTypedDataMessageEntriesInner) Get() *TypedDataMessageEntriesInner {
	return v.value
}

func (v *NullableTypedDataMessageEntriesInner) Set(val *TypedDataMessageEntriesInner) {
	v.value = val
	v.isSet = true
}

func (v NullableTypedDataMessageEntriesInner) IsSet() bool {
	return v.isSet
}

func (v *NullableTypedDataMessageEntriesInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTypedDataMessageEntriesInner(val *TypedDataMessageEntriesInner) *NullableTypedDataMessageEntriesInner {
	return &NullableTypedDataMessageEntriesInner{value: val, isSet: true}
}

func (v NullableTypedDataMessageEntriesInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTypedDataMessageEntriesInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


