/*
AVNU API

REST API documentation for accessing liquidity on Layer 2.  AVNU is a decentralized exchange protocol enabling the fastest and the most efficient operations in DeFi for Layer 2 with better pricing, zero slippage, MEV-protection and gasless trading.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"time"
	"bytes"
	"fmt"
)

// checks if the RegisterReward type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RegisterReward{}

// RegisterReward struct for RegisterReward
type RegisterReward struct {
	// The user's address
	Address string `json:"address"`
	// The name of the company's campaign
	Campaign string `json:"campaign"`
	// The protocol where the reward can be used
	Protocol *string `json:"protocol,omitempty"`
	// The number of free transaction
	FreeTx int64 `json:"freeTx"`
	// Reward's expiration date
	ExpirationDate *time.Time `json:"expirationDate,omitempty"`
	// The list of whitelisted calls
	WhitelistedCalls []WhitelistedCall `json:"whitelistedCalls"`
}

type _RegisterReward RegisterReward

// NewRegisterReward instantiates a new RegisterReward object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRegisterReward(address string, campaign string, freeTx int64, whitelistedCalls []WhitelistedCall) *RegisterReward {
	this := RegisterReward{}
	this.Address = address
	this.Campaign = campaign
	this.FreeTx = freeTx
	this.WhitelistedCalls = whitelistedCalls
	return &this
}

// NewRegisterRewardWithDefaults instantiates a new RegisterReward object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRegisterRewardWithDefaults() *RegisterReward {
	this := RegisterReward{}
	return &this
}

// GetAddress returns the Address field value
func (o *RegisterReward) GetAddress() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Address
}

// GetAddressOk returns a tuple with the Address field value
// and a boolean to check if the value has been set.
func (o *RegisterReward) GetAddressOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Address, true
}

// SetAddress sets field value
func (o *RegisterReward) SetAddress(v string) {
	o.Address = v
}

// GetCampaign returns the Campaign field value
func (o *RegisterReward) GetCampaign() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Campaign
}

// GetCampaignOk returns a tuple with the Campaign field value
// and a boolean to check if the value has been set.
func (o *RegisterReward) GetCampaignOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Campaign, true
}

// SetCampaign sets field value
func (o *RegisterReward) SetCampaign(v string) {
	o.Campaign = v
}

// GetProtocol returns the Protocol field value if set, zero value otherwise.
func (o *RegisterReward) GetProtocol() string {
	if o == nil || IsNil(o.Protocol) {
		var ret string
		return ret
	}
	return *o.Protocol
}

// GetProtocolOk returns a tuple with the Protocol field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RegisterReward) GetProtocolOk() (*string, bool) {
	if o == nil || IsNil(o.Protocol) {
		return nil, false
	}
	return o.Protocol, true
}

// HasProtocol returns a boolean if a field has been set.
func (o *RegisterReward) HasProtocol() bool {
	if o != nil && !IsNil(o.Protocol) {
		return true
	}

	return false
}

// SetProtocol gets a reference to the given string and assigns it to the Protocol field.
func (o *RegisterReward) SetProtocol(v string) {
	o.Protocol = &v
}

// GetFreeTx returns the FreeTx field value
func (o *RegisterReward) GetFreeTx() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.FreeTx
}

// GetFreeTxOk returns a tuple with the FreeTx field value
// and a boolean to check if the value has been set.
func (o *RegisterReward) GetFreeTxOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.FreeTx, true
}

// SetFreeTx sets field value
func (o *RegisterReward) SetFreeTx(v int64) {
	o.FreeTx = v
}

// GetExpirationDate returns the ExpirationDate field value if set, zero value otherwise.
func (o *RegisterReward) GetExpirationDate() time.Time {
	if o == nil || IsNil(o.ExpirationDate) {
		var ret time.Time
		return ret
	}
	return *o.ExpirationDate
}

// GetExpirationDateOk returns a tuple with the ExpirationDate field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RegisterReward) GetExpirationDateOk() (*time.Time, bool) {
	if o == nil || IsNil(o.ExpirationDate) {
		return nil, false
	}
	return o.ExpirationDate, true
}

// HasExpirationDate returns a boolean if a field has been set.
func (o *RegisterReward) HasExpirationDate() bool {
	if o != nil && !IsNil(o.ExpirationDate) {
		return true
	}

	return false
}

// SetExpirationDate gets a reference to the given time.Time and assigns it to the ExpirationDate field.
func (o *RegisterReward) SetExpirationDate(v time.Time) {
	o.ExpirationDate = &v
}

// GetWhitelistedCalls returns the WhitelistedCalls field value
func (o *RegisterReward) GetWhitelistedCalls() []WhitelistedCall {
	if o == nil {
		var ret []WhitelistedCall
		return ret
	}

	return o.WhitelistedCalls
}

// GetWhitelistedCallsOk returns a tuple with the WhitelistedCalls field value
// and a boolean to check if the value has been set.
func (o *RegisterReward) GetWhitelistedCallsOk() ([]WhitelistedCall, bool) {
	if o == nil {
		return nil, false
	}
	return o.WhitelistedCalls, true
}

// SetWhitelistedCalls sets field value
func (o *RegisterReward) SetWhitelistedCalls(v []WhitelistedCall) {
	o.WhitelistedCalls = v
}

func (o RegisterReward) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RegisterReward) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["address"] = o.Address
	toSerialize["campaign"] = o.Campaign
	if !IsNil(o.Protocol) {
		toSerialize["protocol"] = o.Protocol
	}
	toSerialize["freeTx"] = o.FreeTx
	if !IsNil(o.ExpirationDate) {
		toSerialize["expirationDate"] = o.ExpirationDate
	}
	toSerialize["whitelistedCalls"] = o.WhitelistedCalls
	return toSerialize, nil
}

func (o *RegisterReward) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"address",
		"campaign",
		"freeTx",
		"whitelistedCalls",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varRegisterReward := _RegisterReward{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varRegisterReward)

	if err != nil {
		return err
	}

	*o = RegisterReward(varRegisterReward)

	return err
}

type NullableRegisterReward struct {
	value *RegisterReward
	isSet bool
}

func (v NullableRegisterReward) Get() *RegisterReward {
	return v.value
}

func (v *NullableRegisterReward) Set(val *RegisterReward) {
	v.value = val
	v.isSet = true
}

func (v NullableRegisterReward) IsSet() bool {
	return v.isSet
}

func (v *NullableRegisterReward) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRegisterReward(val *RegisterReward) *NullableRegisterReward {
	return &NullableRegisterReward{value: val, isSet: true}
}

func (v NullableRegisterReward) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRegisterReward) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


