/*
AVNU API

REST API documentation for accessing liquidity on Layer 2.  AVNU is a decentralized exchange protocol enabling the fastest and the most efficient operations in DeFi for Layer 2 with better pricing, zero slippage, MEV-protection and gasless trading.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the BuildSwapRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &BuildSwapRequest{}

// BuildSwapRequest struct for BuildSwapRequest
type BuildSwapRequest struct {
	// The unique id of the quote
	QuoteId string `json:"quoteId"`
	// The address which will fill the quote. Not required if then taker address was provided during the quote request
	TakerAddress *string `json:"takerAddress,omitempty"`
	// The maximum acceptable slippage of the buyAmount amount. Default value is 5%. This value is ignored if slippage is not applicable to the selected quote
	Slippage float32 `json:"slippage"`
}

type _BuildSwapRequest BuildSwapRequest

// NewBuildSwapRequest instantiates a new BuildSwapRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewBuildSwapRequest(quoteId string, slippage float32) *BuildSwapRequest {
	this := BuildSwapRequest{}
	this.QuoteId = quoteId
	this.Slippage = slippage
	return &this
}

// NewBuildSwapRequestWithDefaults instantiates a new BuildSwapRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewBuildSwapRequestWithDefaults() *BuildSwapRequest {
	this := BuildSwapRequest{}
	return &this
}

// GetQuoteId returns the QuoteId field value
func (o *BuildSwapRequest) GetQuoteId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.QuoteId
}

// GetQuoteIdOk returns a tuple with the QuoteId field value
// and a boolean to check if the value has been set.
func (o *BuildSwapRequest) GetQuoteIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.QuoteId, true
}

// SetQuoteId sets field value
func (o *BuildSwapRequest) SetQuoteId(v string) {
	o.QuoteId = v
}

// GetTakerAddress returns the TakerAddress field value if set, zero value otherwise.
func (o *BuildSwapRequest) GetTakerAddress() string {
	if o == nil || IsNil(o.TakerAddress) {
		var ret string
		return ret
	}
	return *o.TakerAddress
}

// GetTakerAddressOk returns a tuple with the TakerAddress field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BuildSwapRequest) GetTakerAddressOk() (*string, bool) {
	if o == nil || IsNil(o.TakerAddress) {
		return nil, false
	}
	return o.TakerAddress, true
}

// HasTakerAddress returns a boolean if a field has been set.
func (o *BuildSwapRequest) HasTakerAddress() bool {
	if o != nil && !IsNil(o.TakerAddress) {
		return true
	}

	return false
}

// SetTakerAddress gets a reference to the given string and assigns it to the TakerAddress field.
func (o *BuildSwapRequest) SetTakerAddress(v string) {
	o.TakerAddress = &v
}

// GetSlippage returns the Slippage field value
func (o *BuildSwapRequest) GetSlippage() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.Slippage
}

// GetSlippageOk returns a tuple with the Slippage field value
// and a boolean to check if the value has been set.
func (o *BuildSwapRequest) GetSlippageOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Slippage, true
}

// SetSlippage sets field value
func (o *BuildSwapRequest) SetSlippage(v float32) {
	o.Slippage = v
}

func (o BuildSwapRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o BuildSwapRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["quoteId"] = o.QuoteId
	if !IsNil(o.TakerAddress) {
		toSerialize["takerAddress"] = o.TakerAddress
	}
	toSerialize["slippage"] = o.Slippage
	return toSerialize, nil
}

func (o *BuildSwapRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"quoteId",
		"slippage",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varBuildSwapRequest := _BuildSwapRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varBuildSwapRequest)

	if err != nil {
		return err
	}

	*o = BuildSwapRequest(varBuildSwapRequest)

	return err
}

type NullableBuildSwapRequest struct {
	value *BuildSwapRequest
	isSet bool
}

func (v NullableBuildSwapRequest) Get() *BuildSwapRequest {
	return v.value
}

func (v *NullableBuildSwapRequest) Set(val *BuildSwapRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableBuildSwapRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableBuildSwapRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBuildSwapRequest(val *BuildSwapRequest) *NullableBuildSwapRequest {
	return &NullableBuildSwapRequest{value: val, isSet: true}
}

func (v NullableBuildSwapRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBuildSwapRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


